# **Ejercicios - Tarea**





Ejercicios 1,2,3,4,5,6,9,10,14,15 del tema de Relaciones del libro Rosen_MD_7th_edition que se encuentra en las paginas 596-597

## **Ejercicio 01**

Ejercicio 01 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=14wal9d7Ei4oWlpy6yBcivvdn046sa06L" width="500">


Enunciado traducido:


Representa cada una de estas relaciones en {1, 2, 3} con una matriz (con los elementos de este conjunto enumerados en orden creciente).

a) {(1, 1), (1, 2), (1, 3)}

b) {(1, 2), (2, 1), (2, 2), (3, 3)}

c) {(1, 1), (1, 2), (1, 3), (2, 2), (2, 3), (3, 3)}

d) {(1, 3), (3, 1)}

In [14]:
import numpy as np

# Definición del conjunto A y las relaciones R
A = [1,2,3]
Ra = [(1,1), (1,2), (1,3)]
Rb = [(1,2),(2,1),(2,2),(3,3)]
Rc = [(1,1),(1,2),(1,3),(2,2),(2,3),(3,3)]
Rd = [(1,3),(3,1)]

def crear_matriz(A, relacion):
    """ Función para generar una matriz de adyacencia a partir de una relación. """
    matriz = np.zeros((len(A), len(A)), dtype=int)
    for (a, b) in relacion:
        i, j = A.index(a), A.index(b)
        matriz[i, j] = 1
    return matriz

# Matrices de las relaciones y el conjunto A = [1,2,3]
inciso_a = crear_matriz(A, Ra)
inciso_b = crear_matriz(A, Rb)
inciso_c = crear_matriz(A, Rc)
inciso_d = crear_matriz(A, Rd)

#Mostrar todas las matrices
print("Matriz A_Ra:\n", inciso_a)
print("\nMatriz A_Rb:\n", inciso_b)
print("\nMatriz A_Rc:\n", inciso_c)
print("\nMatriz A_Rd:\n", inciso_d)

Matriz A_Ra:
 [[1 1 1]
 [0 0 0]
 [0 0 0]]

Matriz A_Rb:
 [[0 1 0]
 [1 1 0]
 [0 0 1]]

Matriz A_Rc:
 [[1 1 1]
 [0 1 1]
 [0 0 1]]

Matriz A_Rd:
 [[0 0 1]
 [0 0 0]
 [1 0 0]]


## **Ejercicio 02**


Ejercicio 02 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1Dfp6h5kV9d5SsgrzJTi6ezAySJRRv-na" width="500">


Enunciado traducido:

Representa cada una de estas relaciones en {1, 2, 3, 4} con una matriz (con los elementos de este conjunto enumerados en orden creciente).

a) {(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3,4)}

b) {(1, 1), (1, 4), (2, 2), (3, 3), (4, 1)}

c) {(1, 2), (1, 3), (1, 4), (2, 1), (2, 3), (2, 4), (3, 1), (3,2) , (3, 4), (4, 1), (4, 2), (4,3)}

d) {(2, 4), (3, 1), (3, 2), (3, 4)}

In [13]:
import numpy as np

# Definición del conjunto A y las relaciones R
A = [1,2,3,4]
Ra = [(1,2), (1,3), (1,4), (2,3), (2,4), (3,4)]
Rb = [(1,1), (1,4), (2,2), (3,3), (4,1)]
Rc = [(1,2),(1,3),(1,4),(2,1),(2,3), (2,4), (3,1), (3,2), (3,4), (4,1), (4,2), (4,3)]
Rd = [(2,4),(3,1), (3,2), (3,4)]

def crear_matriz(A, relacion):
    """ Función para generar una matriz de adyacencia a partir de una relación. """
    matriz = np.zeros((len(A), len(A)), dtype=int)
    for (a, b) in relacion:
        i, j = A.index(a), A.index(b)
        matriz[i, j] = 1
    return matriz

# Matrices de las relaciones y el conjunto A = [1,2,3]
inciso_a = crear_matriz(A, Ra)
inciso_b = crear_matriz(A, Rb)
inciso_c = crear_matriz(A, Rc)
inciso_d = crear_matriz(A, Rd)

#Mostrar todas las matrices
print("Matriz A_Ra:\n", inciso_a)
print("\nMatriz A_Rb:\n", inciso_b)
print("\nMatriz A_Rc:\n", inciso_c)
print("\nMatriz A_Rd:\n", inciso_d)

Matriz A_Ra:
 [[0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]
 [0 0 0 0]]

Matriz A_Rb:
 [[1 0 0 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]]

Matriz A_Rc:
 [[0 1 1 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]

Matriz A_Rd:
 [[0 0 0 0]
 [0 0 0 1]
 [1 1 0 1]
 [0 0 0 0]]


## **Ejercicio 03**


Ejercicio 03 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1G6vDBCUQ0Dnbt5lmUy93sB6VsYqsfcEQ" width="500">



Enunciado traducido:

Enumere los pares ordenados en las relaciones en {1, 2, 3} correspondientes a estas matrices (donde las filas y columnas corresponden a los números enteros enumerados en orden creciente).

In [12]:
# Definicion del conjunto A y las matrices
A = [1,2,3]

Ma = [
    [1,0,1],
    [0,1,0],
    [1,0,1],
]

Mb = [
    [0,1,0],
    [0,1,0],
    [0,1,0],
]

Mc = [
    [1,1,1],
    [1,0,1],
    [1,1,1],
]

def pares_ordenados(A, matriz):
  relacion = []
  for i in range(len(A)):
    for j in range(len(A)):
      if matriz[i][j] == 1:
        relacion.append((A[i], A[j]))

  return relacion

# Relaciones de las matrices y el conjunto A = [1,2,3]
inciso_a = pares_ordenados(A, Ma)
inciso_b = pares_ordenados(A, Mb)
inciso_c = pares_ordenados(A, Mc)

# Mostrar todas las relaciones o pares ordenados
print("Relaciones del inciso A: ", inciso_a)
print("Relaciones del inciso B: ", inciso_b)
print("Relaciones del inciso C: ", inciso_c)

Relaciones del inciso A:  [(1, 1), (1, 3), (2, 2), (3, 1), (3, 3)]
Relaciones del inciso B:  [(1, 2), (2, 2), (3, 2)]
Relaciones del inciso C:  [(1, 1), (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2), (3, 3)]


## **Ejercicio 04**


Ejercicio 04 del libro de Rosen 7th edition.

<img src="https://drive.google.com/uc?id=1zcj7mVUqswV4z3uay8_dciznAXhPV0kw" width="500">


Enunciado traducido:

Enumere los pares ordenados en las relaciones de {1, 2, 3, 4} correspondientes a estas matrices (donde las filas y columnas corresponden a los números enteros enumerados en orden creciente).

In [11]:
# Definicion del conjunto A y las matrices
A = [1,2,3,4]

Ma = [
    [1,1,0,1],
    [1,0,1,0],
    [0,1,1,1],
    [1,0,1,1],
]

Mb = [
    [1,1,1,0],
    [0,1,0,0],
    [0,0,1,1],
    [1,0,0,1],
]

Mc = [
    [0,1,0,1],
    [1,0,1,0],
    [0,1,0,1],
    [1,0,1,0],
]

def pares_ordenados(A, matriz):
  relacion = []
  for i in range(len(A)):
    for j in range(len(A)):
      if matriz[i][j] == 1:
        relacion.append((A[i], A[j]))

  return relacion

# Relaciones de las matrices y el conjunto A = [1,2,3]
inciso_a = pares_ordenados(A, Ma)
inciso_b = pares_ordenados(A, Mb)
inciso_c = pares_ordenados(A, Mc)

# Mostrar todas las relaciones o pares ordenados
print("Relaciones del inciso A: ", inciso_a)
print("Relaciones del inciso B: ", inciso_b)
print("Relaciones del inciso C: ", inciso_c)

Relaciones del inciso A:  [(1, 1), (1, 2), (1, 4), (2, 1), (2, 3), (3, 2), (3, 3), (3, 4), (4, 1), (4, 3), (4, 4)]
Relaciones del inciso B:  [(1, 1), (1, 2), (1, 3), (2, 2), (3, 3), (3, 4), (4, 1), (4, 4)]
Relaciones del inciso C:  [(1, 2), (1, 4), (2, 1), (2, 3), (3, 2), (3, 4), (4, 1), (4, 3)]


## **Ejercicio 05**


Ejercicio 05 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1FQawRBhfY8VNeb2eDOccUw_pDSkcwTST" width="500">


Enunciado traducido:

¿Cómo se puede utilizar la matriz que representa una relación R en un conjunto A para determinar si la relación es irreflexiva?

In [10]:
# Podemos transformar la matriz en una relación y de esa manera probar si la relación es irreflexiva.
# También podemos probar si una matriz es irreflexiva si su diagonal principal es diferente 1, es decir, sus elementos son 0
# Ejemplo, usando la matriz y el conjunto A del problema 3


# Funcion para determinar si una relación es irreflexiva.
def es_irreflexiva(relacion, conjunto):
    return all((x, x) not in relacion for x in conjunto)

# Funcion para transformar un matriz en una relación.
def pares_ordenados(A, matriz):
  relacion = []
  for i in range(len(A)):
    for j in range(len(A)):
      if matriz[i][j] == 1:
        relacion.append((A[i], A[j]))

  return relacion

# Definimos al conjunto A y a la matriz Ma
A = [1,2,3]

Ma = [
    [1,0,1],
    [0,1,0],
    [1,0,1],
]

# Se llama a la funcion pares_ordenados y a la funcion es_irreflexivas
relacion_prueba = es_irreflexiva(pares_ordenados(A, Ma), A)

# Evaluamos si la matriz es irreflexiva.
if relacion_prueba:
    print("La matriz Ma es irreflexiva")
else:
    print("La matriz Ma no es irreflexiva")




# Ahora probemos con una matriz que se da en el problema 4
# Se define al conjunto A (lo denominaremos B) y la matriz Mc
B = [1,2,3,4]

Mc = [
    [0,1,0,1],
    [1,0,1,0],
    [0,1,0,1],
    [1,0,1,0],
]

# Se llama a la funcion pares_ordenados y a la funcion es_irreflexivas
relacion_segunda_prueba = es_irreflexiva(pares_ordenados(B, Mc), B)

# Evaluamos si la matriz es irreflexiva.
if relacion_segunda_prueba:
    print("La matriz Mc es irreflexiva")
else:
    print("La matriz Mc no es irreflexiva")

La matriz Ma no es irreflexiva
La matriz Mc es irreflexiva


## **Ejercicio 06**


Ejercicio 06 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1xCUXUwTwfHB8WouCQGDp0iu1ijTRzuJN" width="500">


Enunciado traducido:

¿Cómo se puede utilizar la matriz que representa una relación R en un conjunto A para determinar si la relación es asimétrica?

In [9]:
# Podemos transformar la matriz en una relación y de esa manera probar si la relación es asimetrica.
# También podemos determinar si una matriz es asimetrica si se cumplen con 2 condiciones:
# 1. Si los elementos de su diagonal principal son ceros.
# 2. Si los elementos que estan en posicion simetrica, son parejas de unos y ceros (o de ceros, es decir, no son pares de uno)
# Ejemplo, usando la matriz y el conjunto A del problema 3


# Funcion para determinar si una relación es asimetrica.
def es_asimetrica(matriz):
    tamanio = len(matriz)
    for i in range(tamanio):
      for j in range(tamanio):
        if i != j:
          if matriz[i][j] == 1 and matriz[j][i] == 0:
            return False
        else:
          if matriz[i][j] == 1:
            return False
    return True

# Funcion para transformar un matriz en una relación.
def pares_ordenados(A, matriz):
  relacion = []
  for i in range(len(A)):
    for j in range(len(A)):
      if matriz[i][j] == 1:
        relacion.append((A[i], A[j]))

  return relacion

# Definimos al conjunto A y a la matriz Mc del problema 3
A = [1,2,3]

Mc = [
    [1,1,1],
    [1,0,1],
    [1,1,1],
]

# Se llama a la funcion pares_ordenados y a la funcion es_simetrica
relacion_prueba = es_asimetrica(Mc)

# Evaluamos si la matriz es asimetrica.
# Dado que la funcion es_simetrica nos devuelve verdadero si la funcion es simetrica, entonces, el opuesto de una matriz simetrica es asimetrica.
if relacion_prueba:
    print("La matriz Mc es asimetrica")
else:
    print("La matriz Mc no es asimetrica")



# Ahora probemos con una matriz que se da en el problema 4
# Se define al conjunto A (lo denominaremos B) y la matriz Mb
B = [1,2,3,4]

Mb = [
    [1,1,1,0],
    [0,1,0,0],
    [0,0,1,1],
    [1,0,0,1],
]

# Se llama a la funcion pares_ordenados y a la funcion es_asimetrica
relacion_segunda_prueba = es_asimetrica(Mb)

# Evaluamos si la matriz es asimetrica.
# Dado que la funcion es_simetrica nos devuelve verdadero si la funcion es simetrica, entonces, el opuesto de una matriz simetrica es asimetrica.
if relacion_segunda_prueba:
    print("La matriz Mb es asimetrica")
else:
    print("La matriz Mb no es asimetrica")

La matriz Mc no es asimetrica
La matriz Mb no es asimetrica


## **Ejercicio 07**


Ejercicio 09 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1IMIHoVIEOHOFt-i94D_euiVsX0cgl4In" width="500">

Enunciado traducido:

¿Cuántas entradas distintas de cero tiene la matriz que representa la relación R en A = {1, 2, 3,..., 100} que consta de los primeros 100 enteros positivos si R es

a) {(a, b) | a > b}

b) {(a, b) | a != b}

c) {(a, b) a = b+1}

d) {(a, b) a = 1}

e) {(a, b) | a*b = 1}

In [8]:
# Se define el conjunto A
A = [a for a in range(1,100+1)]

# Generamos las relaciones en base a las condiciones de cada inciso
relacion_a = [(a,b) for a in A for b in A if a > b]
relacion_b = [(a,b) for a in A for b in A if a != b]
relacion_c = [(a,b) for a in A for b in A if a == (b + 1)]
relacion_d = [(a,b) for a in A for b in A if a == 1]
relacion_e = [(a,b) for a in A for b in A if a*b == 1]

# Ahora calculamos el numero de entradas distintas de cero que debe tener la matriz para cada relacion.
entradas_a = sum(1 for a, b in relacion_a)
entradas_b = sum(1 for a, b in relacion_b)
entradas_c = sum(1 for a, b in relacion_c)
entradas_d = sum(1 for a, b in relacion_d)
entradas_e = sum(1 for a, b in relacion_e)


# Imprimimos el numero de entradas distintas de cero que debe tener la matriz para cada relacion.
print(f"La matriz a) tiene {entradas_a} entradas distintas de cero.")
print(f"La matriz b) tiene {entradas_b} entradas distintas de cero.")
print(f"La matriz c) tiene {entradas_c} entradas distintas de cero.")
print(f"La matriz d) tiene {entradas_d} entradas distintas de cero.")
print(f"La matriz e) tiene {entradas_e} entradas distintas de cero.")

La matriz a) tiene 4950 entradas distintas de cero.
La matriz b) tiene 9900 entradas distintas de cero.
La matriz c) tiene 99 entradas distintas de cero.
La matriz d) tiene 100 entradas distintas de cero.
La matriz e) tiene 1 entradas distintas de cero.


## **Ejercicio 08**


Ejercicio 10 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1_Jw5SR4bpdoCely128la1k3GAlAROCKl" width="500">

Enunciado traducido:

¿Cuántas entradas distintas de cero tiene la matriz que representa la relación R en A = {1, 2, 3,..., 1000}?
los primeros 1000 enteros positivos tienen si R es

a) {(a, b) | a <= b}

b) {(a, b) | a == b+/-1}

c) {(a, b) | a + b == 1000}

d) {(a, b) | a + b <=  1001}

e) {(a, b) | a != 0}

In [7]:
# Se define el conjunto A
A = [a for a in range(1,1000+1)]

# Generamos las relaciones en base a las condiciones de cada inciso
relacion_a = [(a,b) for a in A for b in A if a <= b]
relacion_b = [(a,b) for a in A for b in A if a == b+1 or a == b-1]
relacion_c = [(a,b) for a in A for b in A if a + b == 1000]
relacion_d = [(a,b) for a in A for b in A if a + b <= 1001]
relacion_e = [(a,b) for a in A for b in A if a != 0]

# Ahora calculamos el numero de entradas distintas de cero que debe tener la matriz para cada relacion.
entradas_a = sum(1 for a, b in relacion_a)
entradas_b = sum(1 for a, b in relacion_b)
entradas_c = sum(1 for a, b in relacion_c)
entradas_d = sum(1 for a, b in relacion_d)
entradas_e = sum(1 for a, b in relacion_e)


# Imprimimos el numero de entradas distintas de cero que debe tener la matriz para cada relacion.
print(f"La matriz a) tiene {entradas_a} entradas distintas de cero.")
print(f"La matriz b) tiene {entradas_b} entradas distintas de cero.")
print(f"La matriz c) tiene {entradas_c} entradas distintas de cero.")
print(f"La matriz d) tiene {entradas_d} entradas distintas de cero.")
print(f"La matriz e) tiene {entradas_e} entradas distintas de cero.")

La matriz a) tiene 500500 entradas distintas de cero.
La matriz b) tiene 1998 entradas distintas de cero.
La matriz c) tiene 999 entradas distintas de cero.
La matriz d) tiene 500500 entradas distintas de cero.
La matriz e) tiene 1000000 entradas distintas de cero.


## **Ejercicio 09**


Ejercicio 14 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=15qWGiLO5CYhv2zDNbIKTM8rVUMBZdnPy" width="500">


In [6]:
import numpy as np

# Se define a las matriz en relacion con un conjunto A
Mr1 = [
    [0,1,0],
    [1,1,1],
    [1,0,0],
]

Mr2 = [
    [0,1,0],
    [0,1,1],
    [1,1,1],
]

# Resolvemos cada inciso usando matrices, ya que no tenemos el conjunto A, entonces, realizaremos operaciones con las matrices, debido a que estas matrices representan relaciones con el conjunto A.
inciso_a = np.logical_or(Mr1, Mr2).astype(int) # Union de matrices, es decir, se se agregan todos los elementos que tienen ambas matrices
inciso_b = np.logical_and(Mr1, Mr2).astype(int) # Interseccion de matrices, es decir, se agregan los elementos en comun que tienen ambas matrices
inciso_c = np.array(Mr2) * np.array(Mr1) # Multiplicacion elemento a elemento (Multiplicacion de Hadamard) de matrices
inciso_d = np.array(Mr1) * np.array(Mr1) # Multiplicacion elemento a elemento (Multiplicacion de Hadamard) de matrices
inciso_e = np.logical_xor(Mr1, Mr2).astype(int) # Representa a la diferencia simetrica, es decir, es la union de ambas matrices menos la interseccion de ambas matrices


# Imprimimos en pantalla la solucion a cada inciso.
# Usamos las operaciones de matrices para determinar las operaciones de las relaciones que se solicitan en cada inciso, debido a que nos piden las matrices de estas operaciones de relaciones.
print("Union de R1 y R2: \n", inciso_a)
print("\nInterseccion de R1 y R2: \n", inciso_b)
print("\nMultiplicacion de Hadamard de R2 y R1: \n", inciso_c)
print("\nMultiplicacion de Hadamard de R1 y R1: \n", inciso_d)
print("\nDiferencia simetrica de R1 y R2: \n", inciso_e)

Union de R1 y R2: 
 [[0 1 0]
 [1 1 1]
 [1 1 1]]

Interseccion de R1 y R2: 
 [[0 1 0]
 [0 1 1]
 [1 0 0]]

Multiplicacion de Hadamard de R2 y R1: 
 [[0 1 0]
 [0 1 1]
 [1 0 0]]

Multiplicacion de Hadamard de R1 y R1: 
 [[0 1 0]
 [1 1 1]
 [1 0 0]]

Diferencia simetrica de R1 y R2: 
 [[0 0 0]
 [1 0 0]
 [0 1 1]]


## **Ejercicio 10**


Ejercicio 15 del libro de Rosen 7th edition.


<img src="https://drive.google.com/uc?id=1MsXKKySDs_CZJyKwZsSKjzoT3NvIdYSs" width="500">


In [5]:
import numpy as np

# Se define a la matriz Mr

Mr = [
    [0,1,0],
    [0,0,1],
    [1,1,0],
]


# Resolvemos cada inciso usando matrices.
inciso_a = np.array(Mr) @ np.array(Mr) # Potencia de 2 de la matriz Mr
inciso_b = np.array(Mr) @ np.array(Mr) @ np.array(Mr) # Potencia 3 de la matriz Mr
inciso_c = np.array(Mr) @ np.array(Mr) @ np.array(Mr) @ np.array(Mr) # Potencia de 4 de la matriz Mr

# Imprimimos en pantalla la solucion a cada inciso.
print("Mr elevado a la potencia de 2: \n", inciso_a)
print("\nMr elevado a la potencia de 3: \n", inciso_b)
print("\nMr elevado a la potencia de 4: \n", inciso_c)

Mr elevado a la potencia de 2: 
 [[0 0 1]
 [1 1 0]
 [0 1 1]]

Mr elevado a la potencia de 3: 
 [[1 1 0]
 [0 1 1]
 [1 1 1]]

Mr elevado a la potencia de 4: 
 [[0 1 1]
 [1 1 1]
 [1 2 1]]
